### ISSUE TITLE
`ALL` hook settings in config are overridden by defaults

### ISSUE THREAD

**Issue by jawshooah** [causes/overcommit#117]
Currently, any per-hook settings in `default.yml` override those under `ALL` in the user's `.overcommit.yml`.

For example, say I want to exclude a set of files in my repository for all pre-commit hooks. In my `.overcommit.yml`:

```yaml
PreCommit:
  ALL:
    exclude:
      - 'vendor/**/*'
```

These files may be auto-generated or externally developed (and likely shouldn't be in the repository at all, but that's a separate concern), and may not be assumed to follow the style conventions set forth for the rest of the repository.

However, some hooks already exclude certain types of files by default. For example:

```yaml
HardTabs:
  exclude:
    - '**/*.go'
    - '**/Makefile'
    - '.gitmodules'

TrailingWhitespace:
  exclude:
    - '**/db/structure.sql'
```

These exclusions override those in my settings for all pre-commit hooks, so I have to explicitly override them on a per-hook basis.

This isn't necessarily bad behavior, but I figured it was worth discussing, as it requires the user to know which hooks already have default exclusions in order to override them.
