### ISSUE TITLE
Executing custom rake tasks on precommit

### ISSUE THREAD

**Issue by pratik60** [causes/overcommit#127]
I am trying to create a custom hook, which does that....But am not able to distinguish between successful result or not.

```
# Adding a hook to the overcommit precommit section
module Overcommit::Hook::PreCommit
  class Jasmine < Base
    def run
      result = execute(command)
      unless result.stdout.empty?
        return :fail, "Jasmine Test Cases Failed:\n#{result.stdout}"
      end

      :pass
    end
  end
end
```

In .overcommit.yml
```
PreCommit:  
  Jasmine:
    description: 'Run suite of jasmine test cases'
    command: ['bundle', 'exec', 'rake', 'jasmine:ci']
```

This works perfectly fine, but the only problem is in distinguishing whether the result is a success or fail. 

```
Run suite of jasmine test cases.......................[Jasmine] FAILED
Jasmine Test Cases Failed:
Waiting for jasmine server on 60075...
Waiting for jasmine server on 60075...
Waiting for jasmine server on 60075...
Waiting for jasmine server on 60075...
Waiting for jasmine server on 60075...
Waiting for jasmine server on 60075...
Waiting for jasmine server on 60075...
Waiting for jasmine server on 60075...
jasmine server started.
*.....................

22 specs, 0 failures,
```

Suggestions? Any help would be most welcome...
